---
title: "Fiorisce in riva al porto"
date: "2014-07-11T11:42:29.989Z"
author: "Francesco Turci"
medium-url: "https://medium.com/@francesco_turci/fiorisce-in-riva-al-porto-b45c1b793c03"
format: html
---
Fiorisce in riva al porto la sera senza età:\
si disfa ogni dolore nel vespro rosa-azzurro\
e, a custodir il cuore, accorre\
il sacro cianciare di campane\
qui, su, dalla cattedrale.\
Le acque dimentiche del fiume\
carezzano la riva vanamente, la sponda\
e onda dopo onda redimono i minuti\
sprecati e gli abortiti fiori di limone.\
T'illude un gabbiano come già fu:\
non è qui il mare\
eppure a tu per tu con l'oceano\
sono le nubi che ritornano gaudenti\
ben carche e dolci sospinte dai venti.\
È un fiume che s'insinua fra i tigli alti,\
è un fiume più vero di quest'illuso lago\
che restare qui vorrebbe ma non può:\
sicura è la legge che ti riporta al lido,\
che scioglie le fonti, gli scogli\
il carnevale di risa e sbadigli\
i ponti e le carcasse scoppiate;\
sicura è la legge che pure questa goccia\
al mar senza confini per sempre riconduce.
