---
title: "L’inganno è svanito nell’ultima bruma"
date: "2014-03-04T10:48:21.353Z"
author: "Francesco Turci"
medium-url: "https://medium.com/@francesco_turci/linganno-e-svanito-nellultima-bruma-2fad23a5a0cd"
format: html
---
L'inganno è svanito nell'ultima bruma\
e ora Selene mi scorta nel buio\
mentre un bocciolo -timido ancora-\
scorge una luce, un timore, un augurio.\
Sento l'infamia annegare nel vuoto\
della sua vita perduta per sempre;\
sento il mio petto, impertinente,\
ergersi a scudo per le ultime frecce.\
"Patir per patire", questo il responso\
dell'inseguir un fior mai sbocciato:\
quanti pretesti ho da sempre accettato\
pur di sedermi nel cuore del bosco!\
Pur mi rivedo, aquila grande,\
fattomi servo d'un padron incostante:\
"donar per donarsi", questo il discorso\
d'un batter d'ali per volar in alto\
oltre le vette, oltre i mortali\
che della morte ignorano il passo.\
Alla fin fine, umile in basso,\
ho consumato tutt'il mio pasto:\
e questo vischio che copre le piume\
qui mi ritiene, nell'antro più fosco.

Ma se la Pizia ha davvero ragione\
su questo grano di polvere antica\
ora mi attende una voce amica\
che con quell'olio d'un altro Sole\
libererà le ali mie immense\
per nell'azzurro trovare il colore\
d'un tempo immemore di odio\
o dolore.
