---
title: "Satiro"
date: "2014-03-03T18:54:05.256Z"
author: "Francesco Turci"
medium-url: "https://medium.com/@francesco_turci/satiro-b625b8e87690"
format: html
---
Satiro, hai rapito una stella:\
forse hai ingannato i tuoi occhi\
forse hai taciuto alla mimosa bella\
la vera tua natura, e alla sposa.\
Satiro, io ti compiango:\
calpesti quel flauto nel fango\
occulti la lira in un ghigno\
e nel tumulto notturno il tuo grido\
strappa le lacrime al cielo.\
Stille dolcissime che temo e temo\
coprono me, nel folto del bosco\
mentre il sorriso, che non conosco,\
invade la cruda crosta del vostro gioire\
fatto di nulla di niente di vuoto.\
Satiro, ho pena per te:\
la valle che credi di odori e di rose\
nasconde una bestia, immonda e crudele\
che nelle troppo piovose sere\
sbrana i suoi figli innocenti\
e i sogni di noi, povere genti.\
Satiro, forse immondo sei tu\
forse sei solo d'un mondo più mesto\
dove non conta il gesto d'amore\
ma solo un continuo vacuo rumore\
che sembra vita, che sembra fonte\
ma che a me solo parla

d'una perenne stupida morte.
