---
title: "Non ho rimosso"
date: "2014-06-09T20:04:03.678Z"
author: "Francesco Turci"
medium-url: "https://medium.com/@francesco_turci/non-ho-rimosso-f5aa6f3ab800"
format: html
---
Non ho rimosso -non posso-\
il fragore delle acque turchesi\
che scuotono di onda in onda\
l'immobile anfratto del mio cuore:\
qui viene e diviene sciabordio la schiuma\
-parole inutili e di disincanto- e i rivoli rossi\
trascinano in piena dai monti in rotta\
il carcame grave dall'orrido passato.

Linea come di labbra semichiuse dal perdono\
sottile, misteriosa e in combutta con la Luna,\
risali fra le rocce, sfidando i pini blu\
e mille richiami lontani di sirene ch'hai mai conosciuto.\
Tu ci conduci -forse ci inganni- oltre il nostro porto\
dietro le gole che schiudono un fiore purpureo.

Eppur non posso crederti, fuggevole cammino:\
tu sei ora e soltanto un miraggio nel mio destino;\
torna alle tue estati dorate\
torna alle carezze nel vento\
torna alle ombre presenti in un solo nuovo momento:\
lascia a me la notte e la Luna,\
così che anche le lacrime\
possano avere la loro fortuna.
