---
title: "Scendendo per il faggeto"
subtitle: "lento e lentamente ho immerso i miei passi nel lago e ad uno ad uno ho…"
date: "2015-01-31T19:24:38.131Z"
author: "Francesco Turci"
medium-url: "https://medium.com/@francesco_turci/scendendo-per-il-faggeto-53a0b1d81967"
format: html
---
Scendendo per il faggeto,\
lento e lentamente\
ho immerso i miei passi nel lago\
e ad uno ad uno ho sciolto i miei capelli\
nell'onda dolcissima\
e attesa.\
Ho sciolto le parole nei vagiti di luce lontani\
ad ogni minuto più profondo,\
nel cavo\
intimo del monte.

E poi, senza sapere,\
e poi, e pur volendo,\
le carpe d'argento scorrendo cogli occhi\
ho seguito, come incantato\
per trovarmi dal fondo più dolce e sereno\
a un fiume impetuoso e slavato.

E qui, in pochi cubiti\
che appena bacian le ginocchia,\
ho marciato come perso\
seguendo il corso già tracciato.

Però, dopo tanta pianura senza fronda\
e dopo tanto inutile vagolare,\
eccomi, io, a questa riva rimirando,\
sfioro come del mare l'immenso cuore\
piangendo\
e mi domando se la seta tiepida fra le mia dita\
non sia il bisso\
dalle acque profondissime tornato\
e che m'invita\
al più profondo viaggio.
