---
title: "Ti ho lasciato come un fiore,"
subtitle: "Colta nel prato"
date: "2021-03-02T03:01:19.295Z"
author: "Francesco Turci"
medium-url: "https://medium.com/@francesco_turci/ti-ho-lasciato-come-un-fiore-9ecb532f2ce9"
format: html
---
Ti ho lasciato come un fiore,

Colta nel prato

Dormiente nella notte

Carezzata dalla Luna.

Ti ho lasciato e in quella notte

Ho nascosto i miei passi

\- Un'ombra curva che discende la collina.

E nel cupo, lento remare del mio cuore

Mi sorprende una volpe:

Mi scorge,

Mi onora,

Mi saluta

E mi taglia il passo per ritornare al mistero

di una vita oltre me.

E non capisco

E viro al pianto

Ché la solitudine del mondo s' incrina

senza spasmo

E mi svuota di senso.

Così, col pianto, mi ha sorpreso il pettirosso

Mi ha scrutato

Deliziato

Salutato

Ed è volato via. Come te, in un momento

Mi ha strappato dalla mia commiserazione

E gettato senza pena nella pace insensata ed immanente.

Così, mi hanno trascinato le lacrime giù

Fino al bordo del porto

Dove luci sfocate dalle lenti o dai singulti

Mi hanno accolto.

E mentre barche solitarie fendono il vento

Io aggiungo un passo a un altro

Trascinando l'ombra del passato

E lasciandola lacerarsi nel fragore della vita

oltre me.
